#+TITLE: Notes for settings/setup stuff and tricks for desktop settings.

* Firefox
in about:config I set dom.event.clipboardevents.enabled to `false` to stop sites from stopping me from copy pasting my passwords and stuff. However, this makes copy-paste in google docs not work- so be warned!
* vim
=.vimrc= is kept here under version control. On a new system, simply create a symbolic link to your home directory:

=ln -s ~/bin/.vimrc ~/.vimrc=

* Apple defaults

explore =defaults= tool for quick fixes to common issues

Stop the power chime when the computer is plugged in. 

#+BEGIN_SRC bash :results verbatim 
defaults write com.apple.PowerChime ChimeOnNoHardware -bool true
killall PowerChime
#+END_SRC

Stop icons from bouncing

#+BEGIN_SRC bash :results verbatim 
defaults write com.apple.dock no-bouncing -bool true
killall dock
#+END_SRC

* python and virtualenv

Use the default =venv= provided by python and also use [[https://virtualenvwrapper.readthedocs.io/en/latest/index.html][virtualenvwrapper]] to organize virtual envs

1. start a new environment

#+BEGIN_SRC bash :results verbatim 
mkvirtualenv <env-name> 
#+END_SRC

Flag =--python=pythonX.X= to use different versions of python. Default is the one virtualenv was installed with, which is 3.7 in my case. 

This command activates the environment too. You deactivate it by typing =deactivate= and activate in the future by typing =workon <env-name>=. Tab completion should work fine. 

* git 
Stop windows line endings
