---
- name: clone dotfiles
  block:
    - name: Clone with ssh
      ansible.builtin.git:
        repo: git@github.com:nkicg6/dotfiles.git
        clone: true
        dest: $HOME/dotfiles
        update: yes
  rescue:
    - name: Clone wiht HTTPS if ssh fails
      ansible.builtin.git:
        repo: https://github.com/nkicg6/dotfiles.git
        clone: true
        dest: $HOME/dotfiles
        update: yes
