---
- name: Install essentials (MacOS)
  #requires ansible-galaxy collection install community.general
  community.general.homebrew:
    name: "{{ dependencies }}"
    state: latest
    update_homebrew: false
    upgrade_all: false
  when: ansible_distribution == "MacOSX"

- name: Install essentials (Rocky)
  become: yes
  ansible.builtin.dnf:
    name: "{{ dependencies }}"
    state: latest
    update_cache: true
  when: ansible_distribution == "Rocky"

- name: Install essentials (Ubuntu)
  become: yes
  ansible.builtin.apt:
    name: "{{ dependencies }}"
    state: latest
    update_cache: true
  when: ansible_distribution == "Ubuntu"

- name: Install xclip (Rocky)
  become: yes
  ansible.builtin.dnf:
    name: xclip
    state: present
    update_cache: true
  when: ansible_distribution == "Rocky"

- name: Install c compilers (Rocky)
  become: yes
  ansible.builtin.dnf:
    name:
      - gcc
      - clang
    state: present
    update_cache: true
  when: ansible_distribution == "Rocky"

- name: Install xclip (Ubuntu)
  become: yes
  ansible.builtin.apt:
    name: xclip
    state: present
    update_cache: true
  when: ansible_distribution == "Ubuntu"

